- MK8_1080p/rules.txt
- MK8_1440p/rules.txt
- MK8_2160p/rules.txt
4K alpha (i'm using a 1080p monitor):
4K in MKTV:
Excludes the format used by the backgrounds used at the end of VS Mode/Grand Prix, so they don't appear black.
Also ends up removing the gamepad rescale. I think that should be in a separate pack, as in most cases users won't be looking at the gamepad in this game, and rendering it at a higher res would just burn GPU cycles.
> [MK8] Add "/meta/"less id, fullres alpha, MKTV, fix race end graphic

- Preformance/SuperMario3DWorld_360p/rules.txt
- Preformance/XCX_GCN4Workaround/rules
- Quality/SuperMario3DWorld_1080p/rules.txt
- Quality/SuperMario3DWorld_1440p/rules.txt
- Quality/SuperMario3DWorld_2160p/rules.txt
- Quality/XCX_GCN4Workaround/rules
- README.md
Fixed heatwaves in both SM3DW and Captain Toad:Treasure Tracker, also added workaround for no artifacts on AMD GCN4 GPUs. 
4K internal resolution SM3DW -
4K internal resolution CT:TT-
> SM3DW+CT:TT half-res alpha, XCX GCN4 workaround

- Preformance/SuperMario3DWorld_360p/rules.txt
- Quality - Gamepad/SuperMario3DWorld_1080pGamepad/rules.txt
- Quality - Gamepad/SuperMario3DWorld_1440pGamepad/rules.txt
- Quality - Gamepad/SuperMario3DWorld_2160pGamepad/rules.txt
- Quality/SuperMario3DWorld_1080p/rules.txt
- Quality/SuperMario3DWorld_1440p/rules.txt
- Quality/SuperMario3DWorld_2160p/rules.txt
- README.md
Before quarter-res alpha-
After quarter-res alpha-
Also fixes SM3DW-
> Quarter-Res Alpha

- Quality/XCX_1080p/rules.txt
- Quality/XCX_1440p/rules.txt
- Quality/XCX_2160p/rules.txt
It's rendered at 1024x720, so it needed a seperate overwrite. Seems to work fine.
> [Xenoblade X] Added equipment screen render

- Enthusiast/XCX_2880p/rules.txt
- Enthusiast/XCX_4320p/rules.txt
- Quality/GhostBladeHD_2160p/rules.txt
FIX Dialog will fade instead of black screen
FIX Gamepad probe no longer breaks
FIX Intro movie plays instead of green screen. Decoding is mostly broken
> XCX probe and dialog fix

- Quality/SuperMario3DWorld_1080pUW/patches.txt
Patches.txt for SM3dW and Captain Toad.  I didn't include the gamepad aspect because I didn't see any difference with it changed.  For 1440p UW all floats need to be changed to 2.388.
> Ultra wide patches for SM3dW/Kinopio

- Quality/MK8_1080pUW/patches.txt
- Quality/MK8_2160pUW/patches.txt
Altered the way the aspect ratio is changed for ultrawide packs.  This method corrects the aspect ratio for two player split screen and 3d models on the multiplayer select screen.  Though the latter was close enough that most people probably didn't notice.   This addresses the other half of issue #74 even though it's already closed.
Also separated v4 and v4.1 due to one of the rodata constants being 0x10 off.  Not sure if that could have caused any problems or not.
> Updating MK8 UW patches

- Quality/MK8_1080pUW/patches.txt
- Quality/MK8_2160pUW/patches.txt
Had an invalid group name for version 4.1.
> Corrected group name MK8 UW

- Enhancement/BreathOfTheWild_AARemoval/0f2b9ee517917425_00000000000003c9_ps.txt
When using the 4k and AARemoval pack, the inventory screen still shows broken antialiasing
I might have found a solution for it. Let me know if this doesn't only happen for me, and I'll do a pull request
Here are some examples.
Cropped from 4k, resized 2x with no filter, for the love of pixels
> Fixed Breath of the Wild AARemoval in inventory screen

- Enhancement/BreathOfTheWild_AARemoval/0f2b9ee517917425_00000000000003c9_ps.txt
- Enthusiast/BreathOfTheWild_2880p/0f2b9ee517917425_00000000000003c9_ps.txt
- Enthusiast/BreathOfTheWild_4320p/0f2b9ee517917425_00000000000003c9_ps.txt
- Enthusiast/BreathOfTheWild_5760p/0f2b9ee517917425_00000000000003c9_ps.txt
- Quality/BreathOfTheWild_1080p/0f2b9ee517917425_00000000000003c9_ps.txt
- Quality/BreathOfTheWild_1080pUW/0f2b9ee517917425_00000000000003c9_ps.txt
- Quality/BreathOfTheWild_1440p/0f2b9ee517917425_00000000000003c9_ps.txt
- Quality/BreathOfTheWild_1440pUW/0f2b9ee517917425_00000000000003c9_ps.txt
- Quality/BreathOfTheWild_1800p/0f2b9ee517917425_00000000000003c9_ps.txt
- Quality/BreathOfTheWild_2160p/0f2b9ee517917425_00000000000003c9_ps.txt
- Quality/BreathOfTheWild_2160pUW/0f2b9ee517917425_00000000000003c9_ps.txt
Pretty much a fix as before it wouldn't even work, should definitely work now. A comparision can be seen here: http://screenshotcomparison.com/comparison/118920 . Keep in mind that the one on the left side has BotW Anti-Aliasing and the one on the right has this shader's FXAA enabled. I didn't use any FXAA (or anything else) from my Nvidia GPU to enhance the screenshot. The banding on the background is caused by the screenshot method I used.
> Fixed AA Removal's name as it didn't work before, added comments to those shaders.

- Workaround/BreathOfTheWild_BombAsh/71b06814302a7aad_000000000001c24b_ps.txt
- Workaround/BreathOfTheWild_BombAsh/ea77e7f80b23e7b7_0000000000000000_vs.txt
- Workaround/BreathOfTheWild_BombAsh/rules.txt
Found by Xalphenos and Rajkosto on Discord.
Partially fix thin paper look explosion smoke **on Nvdia** when using **AccurateShaderMul = true**, by using the ones from AccurateShaderMul = min
Shaders dumped from Cemu 1.10.0f and BotW 1.3.1
From Xalphenos, true: ![](http://i.imgur.com/tHAOqGW.jpg)
From Forkinator, min: ![](https://cdn.discordapp.com/attachments/292733452590120961/366420061587767298/fix.jpg)
> Fix explosion smoke by using the min shaders

- Enthusiast/BreathOfTheWild_2880p/12d8627fe9906695_0000000000000079_ps.txt
- Enthusiast/BreathOfTheWild_2880p/6279271034da8f93_0000000000000079_ps.txt
- Enthusiast/BreathOfTheWild_4320p/12d8627fe9906695_0000000000000079_ps.txt
- Enthusiast/BreathOfTheWild_4320p/6279271034da8f93_0000000000000079_ps.txt
- Enthusiast/BreathOfTheWild_5760p/12d8627fe9906695_0000000000000079_ps.txt
- Enthusiast/BreathOfTheWild_5760p/6279271034da8f93_0000000000000079_ps.txt
- Quality/BreathOfTheWild_1080p/12d8627fe9906695_0000000000000079_ps.txt
- Quality/BreathOfTheWild_1080p/6279271034da8f93_0000000000000079_ps.txt
- Quality/BreathOfTheWild_1080pUW/12d8627fe9906695_0000000000000079_ps.txt
- Quality/BreathOfTheWild_1080pUW/6279271034da8f93_0000000000000079_ps.txt
- Quality/BreathOfTheWild_1440p/12d8627fe9906695_0000000000000079_ps.txt
- Quality/BreathOfTheWild_1440p/6279271034da8f93_0000000000000079_ps.txt
- Quality/BreathOfTheWild_1440pUW/12d8627fe9906695_0000000000000079_ps.txt
- Quality/BreathOfTheWild_1440pUW/6279271034da8f93_0000000000000079_ps.txt
- Quality/BreathOfTheWild_1800p/12d8627fe9906695_0000000000000079_ps.txt
- Quality/BreathOfTheWild_1800p/6279271034da8f93_0000000000000079_ps.txt
- Quality/BreathOfTheWild_2160pUW/12d8627fe9906695_0000000000000079_ps.txt
- Quality/BreathOfTheWild_2160pUW/6279271034da8f93_0000000000000079_ps.txt
- Quality/BreathOfTheWild_Switch/12d8627fe9906695_0000000000000079_ps.txt
- Quality/BreathOfTheWild_Switch/6279271034da8f93_0000000000000079_ps.txt
The old way used in menu blur is kinda hacky (cuz later found the games's original blur is
linear sampled 5x5, not jump lines), and seems to have some negative effect when used on bloom (some objects' bloom has ghosting because the offsets are too large)
So back to increasing taps, however as the image size goes up, it becomes quite hard/impossible to get the same blurry result as 320x180 for some reason. 5x5 menu blur ends up with 100 taps in 10k to get the similar blur, and 9x9 used in bloom is even blurrier... so I gave up trying to get the same blur by increasing a lot of taps, but just scale linearly to fix pixelation first and wait for a better solution.
Also the texturesize() returns weird value when mipmap is present, so changed to calculate the image size from the values passed …
> workaround upscaled blur pixelation

- Enthusiast/Splatoon_2880p/rules.txt
- Enthusiast/Splatoon_4320p/rules.txt
- Enthusiast/Splatoon_5760p/rules.txt
- Quality/Splatoon_1080p/rules.txt
- Quality/Splatoon_1080pUW/rules.txt
- Quality/Splatoon_1440p/rules.txt
- Quality/Splatoon_1800p/rules.txt
- Quality/Splatoon_2160p/rules.txt
- Workaround/BreathOfTheWild_BombAsh/2938a1b3abfdfe49_0000000000000000_vs.txt
Also another smoke shader of BotW, report by Bleed.0xx on discord (only vertex, smoke itself seems to be only a texture).
The missing bloom shares the same root cause as BotW's bloom(when up depth), dof(when q-res 816 not scaled) and heatwave(when upscale half-res), according to Exzap, because the game creates a mipmap seperately so cemu won't auto rescale it.
Only added one to avoid the possibility of breaking other things, the rest 3 is then all handled by cemu (tested with 1440p)
before:
after:
> splatoon missing bloom

- appveyor.yml
Once you merge this, there's no turning back. Make sure you only have working templates in your build.sh because anything from the repository will be overwritten by their outputs before being placed in the zip file by AppVeyor.
After you're sure that the templates are building correctly and are equivalent to the files in the repo, you can even delete the ones in the repo, to unclutter commits.
> Execute build.sh during appveyor build phase using Cygwin

- Modifications/XCX_CollectiblesRange/patches.txt
- Modifications/XCX_CollectiblesRange/rules.txt
- Modifications/XCX_CustomDropRatio/patches.txt
- Modifications/XCX_CustomDropRatio/rules.txt
Add 2 new packs. One that increases collectibles range, other that allow customization of drop ratio for enemies loot.
> Add modification packs for Xenoblade Chronicles X

- Enhancement/BreathOfTheWild_ShadowBlurRemoval/ffe0e8c84f6e8da9_000003c000009269_ps.txt
- Enhancement/BreathOfTheWild_ShadowBlurRemoval/rules.txt
@JoelAlone 
Credit @alexkiri found this shader (and also looked into it).
But yea this is a dirty workaround... can't get the same blur atm anyway so might just remove it xD
(also because the coordinates calculation looks complicated...)
Mainly for 4k and up where the 2x2 blur doesn't look like blur anymore
from alucard0712_rus:
from Joel:
The side-effect is that the shadow now look more aliased without blur.
> [BotW] shadow blur removal

- Enhancement/Pokken_HighResShadows/rules.txt
- Source/PokkenTournament/rules.txt
The graphic pack is being enabled only for USA and DEMO version. Add EUR version 00050000101DF500
> Add EUR version to rules.txt for Pokken

- Source/SuperMario3DWorld/patches.txt
Touching the screen when using ultrawide touches the wrong position, this makes sure the position is correct.
Credits: Xalphenos
> [SM3Dworld] Fix for the touch position in ultrawide resolution

- Source/HyruleWarriors/rules.txt
Fix some errors in the normal resolution file, that are affecting the ultrawide modes. 
The original file uses scaleFactorY for width which shouldn't matter for normal scaling but makes some different values when using non-16:9 proportion.
> [HW] Typos in the normal resolution file

- Enhancement/HyruleWarriors_HighResShadows/rules.txt
- Modifications/HyruleWarriors_60FPS/rules.txt
- Workaround/HyruleWarriors_30FPS/rules.txt
- Workaround/HyruleWarriors_DLCFix/rules.txt
- Workaround/HyruleWarriors_DoFBlurRemoval/rules.txt
- Workaround/HyruleWarriors_EnemyDeathFix/rules.txt
- Workaround/HyruleWarriors_ShadowRemoval/rules.txt
JP v272 RPX matches EU/US v208, all patches seem to work fine on it too.
> [HW] Add support for JP release

- Source/BreathOfTheWild_StaticFPS/patches.txt
- Source/BreathOfTheWild_StaticFPS/readme.txt
This fixes the infamous arrow distance bug at !=30FPS by changing two relevant floats accordingly (and the comments include how the calculation is done). It's a product of trial and error, basic ideas and some luck.
The current patch applies to the static FPS mod. FPS++ will be likely fixed by Xalphenos.
> Fix for the physics of Arrow projectiles

- Source/HyruleWarriors/rules.txt
Changed the height amount, as it was set to the wrong value.
Now the game properly renders the gamepad screen at the desired resolution.
[Before image](https://i.imgur.com/jcYOfDT.jpg)
[After image](https://i.imgur.com/5BlHqHc.jpg)
> [Hyrule Warriors] Fixed coop-gamepad resolution

- Modifications/BreathOfTheWild_FPS++/rules.txt
More intuitive than an "uncapped" option hidden in a submenu IMO and having multiple FPS limit presets is very useful for avoiding screen tear on adaptive refreshrate displays (Free- and G-Sync).
Solves #249 .
> Add FPS limit presets to BOTW FPS++

- Source/Bayonetta_Resolution/rules.txt
Changed the format section of the texture redefine from "formatsExcluded =" to "formats = 0x001a" allowing the game to boot again with the res pack enabled.
As a side note I did not see any other texture formats using 8x8 resolution besides 0x001a
> Fixed 8x8 Texture redefine in Bayonetta 1 Res pack

- Workarounds/eShop_RemoveGrayOverlay/fcd26205b94e11ca_000000000000001f_ps.txt
- Workarounds/eShop_RemoveGrayOverlay/fcd26205b94e11ca_0000000000000079_ps.txt
- Workarounds/eShop_RemoveGrayOverlay/rules.txt
For some reason eShop renders a gray square/overlay over the lower half of the TV output.
Screenshot of the problem:
The pack modifies the overlay render shader to discard all pixels. Doesn't seem to have any negative side effects
> Added workaround pack for eShop

- Resolutions/BreathOfTheWild_Resolution/rules.txt
i've added the resolution 3840x1600 (21:10) for BotW.
i own a LG 38WK95C-W which runs at 3840x1600 and its resolution was missing.
> [BotW] 38" ultrawide resolution (3840x1600) added

- Resolutions/BreathOfTheWild_Resolution/cb0e6e8cbec4502a_0000000000000079_ps.txt
By sampling at the 2x2 center of 4 adjacent texels, we get the average of the squad at once. Reducing 64 samples to 16 at 1440p.
I believe this is what the game was doing as well:
1. the result texture is set to half the original res.
2. the shift in coordinates is 1 seen in the vertex shader.
It means that instead of sampling at the texel center of textureUnitPS0, it samples at the 4 corner of the 2x2 square. For GPU's linear interpolation, each sampling gives the average value of 4 neighboring texels, together it gets all 16 texels in the 4x4 square... with just 4 fetches.
We can mimic this in our circular blur shader. The result at 1440p is slightly less blurry than native 720p when using sheikah scope. But I don't think it's completely because of this shader, as the sheikah scope uses …
> [BotW] Circular blur: cut costs with linear

- Resolutions/BreathOfTheWild_Resolution/rules.txt
...And other texture cache's mismatch warnings.
Uncomment 128x64 for a scope DOF fix at line 760 if HUD setting is Pro, since the game doesn't draw the sound HUD.
Resizing 0x1,0x1a has the risk of breaking textures, tho there wasn't any game texture matching the resolution and format in Nsight resource tab. I haven't notice any obvious breaking while playing.
Separate slices of Cubemap being caught by 32x16 resize is not fixed. It needs too many 0x816, 0x1a resizes to not have texture mismatches.
Also I changed to file to Windows(CR LF), thus the diff...
What was 1/10 resolution intended for?
1/10 resized, missing bloom and ambient lighting('red filter').
native, the fixed version looks the same.
I have no idea what the game is doing with this, it's prepared with blurs but not getting …
> [BotW] Fix 960x540 background ambient light, bloom

- Mods/BreathOfTheWild_ChangeAncientGlowColor/Readme.txt
- Resolutions/BreathOfTheWild_Resolution/rules.txt
For many cutscenes the game draw the subtitles on a 500x94 box first and apply the box with the letters onto the screen. Resized the box to make subtitles less blurry.
Text bloom/effect use another 560x150 box, it's good not having to resize it.
The pop up message is also sharper after resizing, but looks like it might have been over-sampled a bit.
> [BotW] Resize letters box to make text less blurry

- Filters/Bicubic (4 taps)/output.glsl
- Filters/Bicubic (4 taps)/rules.txt
- Filters/Bicubic/output.glsl
- Filters/Bicubic/rules.txt
- Filters/Jinc/output.glsl
- Filters/Jinc/rules.txt
Add your titleID in rules.txt for them to work.
Updated Cemuhook's Bicubic and Lanczos scaling shader.
Bicubic was recently optimized by the author at OBS to use 9 taps instead of 16. Cemu's Hermite is the Catmull-rom preset.
Fixed Jinc (Lanczos) shader's divide by zero check. So there is no longer black dotted lines artifact when not zooming.
> Add scaling filters

- Workarounds/WindWakerHD_PictoBox/patches.txt
- Workarounds/WindWakerHD_PictoBox/readme.txt
- Workarounds/WindWakerHD_PictoBox/rules.txt
Added workaround for 'Lenzo's Research Assistant' quest. Lezlo will now accept any picture shown. Works with USA and EUR versions.
> [Wind Waker HD] Added Picto-Box workaround

- Enhancements/BreathOfTheWild_Clarity/37040a485a29d54e_00000000000003c9_ps.txt
- Enhancements/BreathOfTheWild_Clarity/rules.txt
- Enhancements/BreathOfTheWild_LODBias/rules.txt
- Mods/BreathOfTheWild_Cheats_FasterArrowDraw/rules.txt
- Mods/BreathOfTheWild_Cheats_InfArrows/rules.txt
- Mods/BreathOfTheWild_Cheats_InfDaruk/rules.txt
- Mods/BreathOfTheWild_Cheats_InfHearts/rules.txt
- Mods/BreathOfTheWild_Cheats_InfMipha/rules.txt
- Mods/BreathOfTheWild_Cheats_InfMotorcycle/rules.txt
- Mods/BreathOfTheWild_Cheats_InfRevali/rules.txt
- Mods/BreathOfTheWild_Cheats_InfStamina/rules.txt
- Mods/BreathOfTheWild_Cheats_InfUrbosa/rules.txt
- Mods/BreathOfTheWild_Cheats_InfWeapons/rules.txt
- Mods/BreathOfTheWild_Cheats_MotorcycleAnywhere/rules.txt
- Mods/BreathOfTheWild_DayLength/rules.txt
- Mods/BreathOfTheWild_FPS++/Dynamic Gamespeed/rules.txt
- Mods/BreathOfTheWild_FPS++/Fence Method/rules.txt
- Mods/BreathOfTheWild_FPS++/Limit FPS/rules.txt
- Mods/BreathOfTheWild_FPS++/Occlusion Query/rules.txt
- Mods/BreathOfTheWild_NoMMTriforce/rules.txt
- Mods/BreathOfTheWild_StaticFPS/rules.txt
- Mods/BreathOfTheWild_Weather/rules.txt
For packs without shaders, this is just changing the version field to 4. For all others the shaders need to be updated. The experimental Vulkan renderer will only load custom shaders if the version is set to 4.
Updating shaders mainly involves replacing the input/outputs (textures, attributes, uniforms) with the new header generated by Cemu 1.15.19 and WIP 1.16.0. In some cases parts of the main() code need to adjusted as well (e.g. use new macros for gl_FragCoord, gl_Position, gl_VertexID, gl_InstanceID)
I included an updated Clarity shader as an example in this commit.
> Updated some gfx packs to v4

- Workarounds/BreathOfTheWild_LwzxNullCheck/rules.txt
add "(OpenGL)" to title and rendererFilter to this pack since it creates crashes on vulkan and is not nessecary due enforcement of GX2DrawDone on vulkan
> [BOTW] add rendererFilter to LWZX Crash Pack

- Workarounds/ColorSplash_InvisibleCharactersCutoutMode/f98d1c67b6e7d097_0000000000000000_vs.txt
- Workarounds/ColorSplash_InvisibleCharactersCutoutMode/rules.txt
This is a small fix to render Mario and the flag over the background during cutouts sequences. 
[Example](https://gfycat.com/soulfuldistortedcaribou).
> [Paper Mario: CS] Fix the invisible characters in Cutout Mode

- Resolutions/WindWakerHD_Resolution/rules.txt
Using just that part of the code, the camera returned to working properly at resolutions lower than 1080p, on ultrawide resolutions it remains the same before this fix.
Video showing the fix:https://streamable.com/ovtvvg
> Pictograph fix

- Resolutions/BreathOfTheWild_Resolution/rules.txt
A fairly trivial addition, heavily requested by those with 32:9 monitors such as the Samsung Odyssey G9
> [BotW] Add 32:9 resolutions

- src/BreathOfTheWild/Mods/DivineLaserBeam/6fa2baef8a4ece42_0000000000000709_ps.txt
- src/BreathOfTheWild/Mods/DivineLaserBeam/de960d36a997b34d_0000000000000709_ps.txt
- src/BreathOfTheWild/Mods/DivineLaserBeam/rules.txt
Let me join the excitement for BotW v6 packs 😛 
Since the first version of the pack made by Kiri, it was possible to change beams saturation and transparency by manually editing the shaders.
When I ported the pack to version 3, it wasn't possible to have preset categories, so I couldn't add a way to change those two options in the UI. But now we can, so I did it! 🎉 
Users can now choose between 100%, 75%, 50% and 25% for color saturation. For transparency is the same, plus a 10% option (for those who prefer barely visible beams).
I've also reworded the enable/disable beams preset to be a little clearer and hidden all color options if beams are disabled.
PS: there is third settable constant in the shaders, which is "value". I didn't make it editable from the UI because it seemed to behave …
> [BotW] DivineLaserBeams: Make transparency and saturation settable + UX improvements

- src/BreathOfTheWild/Mods/FPS++/patch_GameSpeed.asm
The issue is related to increased vertical sensitivity in stasis and magnesis while running at higher FPS.
> [BotW] FPS++, Added fixes for vertical sensitivity

- src/SonicBoomRiseOfLyric/Mods/DisableVersionString/patch_DisableVersionString.asm
- src/SonicBoomRiseOfLyric/Mods/DisableVersionString/rules.txt
Hides the version string that lingers around on the menus in the patched version of the game.
> [Sonic Boom] Disable Version String patch

- src/SonicBoomRiseOfLyric/Mods/DevLevelSelect/rules.txt
- src/SonicBoomRiseOfLyric/Mods/DisableIntroLogos/patch_DisableIntroLogos.asm
- src/SonicBoomRiseOfLyric/Mods/DisableIntroLogos/rules.txt
Disables the unskippable logos that appear at the start of the game that take a horrifically long time to pass.
> [Sonic Boom] Disable Intro Logos patch

- src/SonicBoomRiseOfLyric/Mods/FixPauseStateReset/patch_FixPauseStateReset.asm
- src/SonicBoomRiseOfLyric/Mods/FixPauseStateReset/rules.txt
Fixes a silly bug where all players reset their states to idle after unpausing the game.
> [Sonic Boom] Fix Pause State Reset

- src/SonicBoomRiseOfLyric/Cheats/UnlockAllMoneyBags/patch_UnlockAllMoneyBags.asm
- src/SonicBoomRiseOfLyric/Cheats/UnlockAllMoneyBags/rules.txt
Bypasses that dumb 3DS requirement for some extra rings.
> [Sonic Boom] Unlock All Money Bags

- src/SonicBoomRiseOfLyric/Enhancements/DisableEventCameraShake/patch_DisableEventCameraShake.asm
- src/SonicBoomRiseOfLyric/Enhancements/DisableEventCameraShake/rules.txt
- src/SonicBoomRiseOfLyric/Enhancements/DisablePlayerCameraShake/patch_DisablePlayerCameraShake.asm
- src/SonicBoomRiseOfLyric/Enhancements/DisablePlayerCameraShake/rules.txt
Two separate patches that disable either player-related camera shake or event-related camera shake.
If patch conditions are introduced to Cemu in the future, these may be combined into a single graphic pack - for the sake of everyone's sanity, they are separate for now.
> [Sonic Boom] Disable Camera Shake

- src/SonicBoomRiseOfLyric/Cheats/InfiniteRobotScrap/patch_InfiniteRobotScrap.asm
- src/SonicBoomRiseOfLyric/Cheats/InfiniteRobotScrap/rules.txt
- src/SonicBoomRiseOfLyric/Cheats/InfiniteTotalRings/patch_InfiniteTotalRings.asm
- src/SonicBoomRiseOfLyric/Cheats/InfiniteTotalRings/rules.txt
Two separate patches that award the player with 999,999 robot scrap and 999,999 total rings.
The former is kinda useless for upgrades right now, as infinite crowns are yet to be figured out.
Soon™
> [Sonic Boom] Infinite Currency

- src/SonicBoomRiseOfLyric/Mods/DisableHUD/patch_DisableHUD.asm
- src/SonicBoomRiseOfLyric/Mods/DisableHUD/rules.txt
Disables the main heads-up display, player markers, objective markers and subtitles.
> [Sonic Boom] Disable HUD

- src/SonicBoomRiseOfLyric/Cheats/DisableComboReset/patch_DisableComboReset.asm
- src/SonicBoomRiseOfLyric/Cheats/DisableComboReset/rules.txt
Prevents your combos from expiring regardless, because why not.
> [Sonic Boom] Disable Combo Reset

- src/BreathOfTheWild/Mods/DivineLaserBeam/rules.txt
"Opacity" is more correct than "transparency" here, as 100% makes the beam fully opaque and 10% makes it almost completely transparent.
> Laser Transparency -> Laser Opacity

- src/XenobladeChroniclesX/Mods/BattleEscapeDistance/rules.txt
- src/XenobladeChroniclesX/Mods/BladeGainTicketsFromMissions/rules.txt
- src/XenobladeChroniclesX/Mods/BladeGlobalNemesisMissionsOffline/patch_offline_nemesis.asm
- src/XenobladeChroniclesX/Mods/BladeGlobalNemesisMissionsOffline/rules.txt
- src/XenobladeChroniclesX/Mods/BladeTasksAndMissionsOffline/patch_offline_squad.asm
- src/XenobladeChroniclesX/Mods/BladeTasksAndMissionsOffline/rules.txt
- src/XenobladeChroniclesX/Mods/ExpBladePointsX/patch_exp_blade.asm
- src/XenobladeChroniclesX/Mods/HUDFreecam/rules.txt
- src/XenobladeChroniclesX/Mods/WeatherForceWeather/rules.txt
There were some unused weather conditions that the weather mod could access so I added those. The weather mod can also lock the current weather which can get weather in places its not supposed to be so I added an option for that.
I also fixed 1.0.2J support in the blade point multiplier.
small feature update to global nemesis offline as well
E fix: Was just discovered that Blade missions offline could be used to grief currently active online missions. Added a line in the .asm to kill the online (same as enemy stats mod). Also added troubleshooting text for a common issue that already existed with the mod.
also also, unrelated question to the pull request but in Graphics pack v708, XCX has a brightness fix that seems to work better than the current one. It works better for me than the …
> [Xenoblade X] Adds support for unused weather conditions | Also fixes a mod that could be used for online griefing

- Workarounds/KirbyRainbow_InvisibleLineFix/ebdd1eb96ab75207_0000000000000000_vs.txt
- Workarounds/KirbyRainbow_InvisibleLineFix/rules.txt
Occasionally the z component of gl_Position gets set to -175 which then causes the line to get clipped. As a workaround we always force z to 0.5 (the expected value)
> [Kirby Rainbow Curse] Add workaround for invisible lines

- src/Splatoon/Graphics/patches.txt
- src/Splatoon/Mods/!NoHUD/patches.txt
- src/Splatoon/Mods/30FPS/patches.txt
- src/Splatoon/Mods/60FPSPlaza/patches.txt
- src/Splatoon/Mods/MapSwap/patches.txt
- src/Splatoon/Mods/Octohax/patches.txt
- src/Splatoon/Mods/SquidSisterSwap/patches.txt
Outside from the addresses for the 30FPS and Ultrawide HUD patches, all of the addresses stayed intact in the latest update.
> [Splatoon] Add 2.12.1 support.

- src/M&SSochi2014/Graphics/rules.txt
Fixes a strange resolution bug in Mario & Sonic Rio Olympic Games 2016 by updating the code to match Sonic Lost World and adds a Sochi Winter Games 2014 resolutions file as well. 
Not tested extensively for M&S Winter 2014 because of an emulation bug causing crashes a few seconds after the title screen, making it unplayable.
Closes #605 and #606 (2014 runs at 60 FPS consistently though afaik)
> M&S Olympic Games Resolution fixes

- src/MarioKart8/Graphics/rules.txt
Fixed an issue where on the results screen of a Grand Prix race there would be a black bar on the scoreboard.
before:
after:
The normal rendering of the scoreboard uses a texture of 576x64 and copies it to a smaller texture of 560x64:
However the resolution graphic pack puts the source image at the same resolution as the destination, so the image copy doesn't cut off the black/undefined part which shows in the final output.
> MK8: Fix cup screen black lines

- src/Splatoon/Graphics/rules.txt
> [Splatoon] Fix black sky in Arowana Mall

- src/SkylandersSuperChargers/Mods/FPS/patch_FixInfiniteFall.asm
- src/SkylandersSuperChargers/Mods/FPS/rules.txt
- src/SkylandersSwapForce/Mods/FPS/patch_FixInfiniteFall.asm
- src/SkylandersSwapForce/Mods/FPS/rules.txt
Fixes one of the issues caused by higher framerates in the Skylanders saga: #615.
The reason why the character was respawning during long falls is because of a failsafe meant in case your character is stuck falling between geometry.
The game determines whether you are stuck with a simple method: it calculates the squared distance of your character from the position of the previous frame, then checks whether it's lower than 20². If that's true for 3 seconds, then it teleports you.
But if the framerate is higher, your distance is going to be lower than normal, and the game will consider you stuck even when falling at top speed.
Ironic...
The fix simply consists in overriding the load of 20.0, and load `20×30FPS/targetFPS` instead.
(Ideally you would multiply by `deltaTime` instead of …
> Skylanders: Fix infinite fall softlock at high FPS

- src/BreathOfTheWild/Enhancements/37040a485a29d54e_00000000000003c9_ps.txt
- src/BreathOfTheWild/Enhancements/rules.txt
01
**With** clarity preset:
Without clarity preset:
02
**With** clarity preset:
Without clarity preset:
03
**With** clarity preset:
Without clarity preset:
I've been playing ~10 hours all around with this preset so far and really enjoying it, seems to work well in all areas. It gets rid of that vanilla desaturation basically. A lot of presets change the overall colors too much. I wanted something closer to vanilla just more saturated. I went through and tried all the existing presets and this one still feels like a unique add.
[Ready to merge]
> BOTW clarity preset "Cobalt (Saturated & Bright)" [Ready to Merge]

- src/BreathOfTheWild/Enhancements/rules.txt
- src/BreathOfTheWild/Graphics/rules.txt
For a consistent UX-Experience, Presets considered as "LOW" or "OFF" should always be put on top, while "HIGH" or "ON" should be on the bottom, eg `low -> medium -> high -> max`
The BOTW GraphicPacks category seems like it could not decide, and just screwed the order entirely, leading to some doing it like this, and some like that.
This PR re-orders the options from the Enhancements and Graphics categories. I left others untouched (eg Cheats and Mods), because they apparently follow the `default -> non-default` order. 
Would close #591
> [BOTW] Make Option-Orders consistent

- src/SonicBoomRiseOfLyric/Mods/FixPauseStateReset/rules.txt
Adding as a note after watching a friend play the game and question why the glitch wasn't working, then seeing this pack enabled lol
> [Rise of Lyric] Note Knuckles jump glitch in Fix Pause State Reset

- Workarounds/MinecraftWiiUEdition_NetworkPort/patch_port.asm
- Workarounds/MinecraftWiiUEdition_NetworkPort/rules.txt
- src/MarioKart8/NetworkPort/patch_port.asm
- src/MarioKart8/NetworkPort/rules.txt
- src/Splatoon/NetworkPort/patch_port.asm
- src/Splatoon/NetworkPort/rules.txt
Wii U games have pretty dated netcode that can struggle with modern networks, leading to 118- errors when playing online. Nintendo's recommendation is to place the game in the DMZ, effectively forwarding every port to it. This isn't really viable for most users.
These patches allow the user to specify a port number that they would like the game to use for all peer-to-peer communications. Then, if the user forwards that UDP port in their router, it's equivalent to the DMZ/"NAT Type A" case and they should get better connectivity. Pretendo plans to ship similar patches to console players so we can maximise the number of port-forwarded users in the online population (the port number will be automatically chosen on hardware - I couldn't work out a good way to do this in Cemu though). …
> [MK8/Splatoon/Minecraft] Add overrides for the peer-to-peer/multiplayer ports

- src/SkylandersGiants/Mods/FPS/patch_dt.asm
- src/SkylandersGiants/Mods/FPS/rules.txt
- src/SkylandersImaginators/Mods/FPS/rules.txt
- src/SkylandersSpyrosAdventure/Mods/FPS/patch_dt.asm
- src/SkylandersSpyrosAdventure/Mods/FPS/rules.txt
- src/SkylandersSwapForce/Mods/FPS/rules.txt
- src/SkylandersTrapTeam/Mods/FPS/patch_dt.asm
- src/SkylandersTrapTeam/Mods/FPS/rules.txt
When going above 120 FPS on Skylanders: Spyro's Adventure, Giants, or Trap Team, the game would speed up.
This is because Toys for Bob went out of their way to explicitly code this behavior.
Why would they do this, especially on games that are console exclusive?[^1] Truly one of humankind biggest mysteries...
Anyway, this PR patches out this behavior, so that the game will always run at the correct speed (except for the things where the developers forgot to multiply by delta time: those aren't fixed.)
(Also took the opportunity to make small changes to the descriptions of the other games.)
Credits to @WinnerNombre for porting the patch to the Wii U games.
[^1]: Before you say "but SSA is also on PC": that version (along with the PS3 and Xbox 360 versions) runs on a completely different …
> [Skylanders] Fix speed-up above 120 FPS (SSA, SG and STT)

- src/BreathOfTheWild/Graphics/f14bb57cd5c9cb77_00000000000003c9_ps.txt
FXAA quality at Extreme. Performance remains the same and the result is less pixelated and sharper.
> [BotW] Use Extreme Quality for FXAA

- src/Splatoon/Mods/DPADJump/patch_dpadjump.asm
- src/Splatoon/Mods/DPADJump/rules.txt
I ported the splatoon patches from SwapDRC to Cemu, instead of having to use your mouse to perform a superjump, you can just hold A and then press the D-Pad (it doesn't have to be in this order, but you might accidentally send a signal to your teammates if you do it the other way around).
I tested this several times and it works fine.
> [Splatoon] Superjump With The DPAD (Mod)

- src/SkylandersSwapForce/Mods/Remove Portal Check/patch_RemovePortalCheck.asm
- src/SkylandersSwapForce/Mods/Remove Portal Check/rules.txt
Removes the need to use the portal that came with SWAP-Force (or the games that came after it). This lets you use the Spyro's Adventure or the Giants portal for example.
This is basically the SWAP-Force version of this https://github.com/cemu-project/cemu_graphic_packs/pull/673
> [Skylanders] Remove Portal Check SWAP-Force

- src/SkylandersSwapForce/Mods/Remove Portal Check/rules.txt
I used an old rules.txt I had as a base to make this https://github.com/cemu-project/cemu_graphic_packs/pull/698 and only noticed now that the path in my graphic pack is not consistent with the others, oops.
The path starts with "Skylanders SWAP-Force/..." but the other graphic packs use "Skylanders Swap Force/..."
Sorry about that
> [Skylanders] Fix the path for Remove Portal Check SWAP-Force 

- Workarounds/DisneyEpicMickey2_GreenOverlayFix/patch_greenfix.asm
- Workarounds/DisneyEpicMickey2_GreenOverlayFix/rules.txt
Fixes the green tint over the screen that only appears in Cemu. Still no clue why this happens, but its fixed, so...
> Workaround for Epic Mickey 2 Graphical Issue

- src/SkylandersSuperChargers/Mods/FPS/patch_FixInfiniteFall.asm
- src/SkylandersSwapForce/Mods/FPS/patch_FixInfiniteFall.asm
Fixes #639.
The patch used `r0` as a temporary register. In PowerPC, using `r0` as an argument in load instructions means `0` instead of the value of the register, meaning that we were loading address `00000000`.
Thus, the patch was doing undefined behavior, and was breaking the intended behavior of the function that was patched (respawning you when you are *actually* stuck). Whoops...
Now it uses `r3` instead.
> Skylanders: Use `r3` in the falling respawn fixes

- src/BreathOfTheWild/Mods/FPS++/rules.txt
90 FPS option was missing for Advanced Mode in FPS++
Needed it for my 180Hz display ([AOC 24G4X](https://aoc.com/us/gaming/products/monitors/24g4x))
> [BotW] Add 90 FPS preset for Advanced Mode in FPS++
