cemu-project/cemu_graphic_packs

Preformance/MK8_360p/rules.txt
Quality - Gamepad/MK8_1080pGamepad/rules.txt
Quality - Gamepad/MK8_1440pGamepad/rules.txt
Quality - Gamepad/MK8_2160pGamepad/rules.txt
Quality/MK8_1080p/rules.txt
Quality/MK8_1440p/rules.txt
Quality/MK8_2160p/rules.txt

Mario Kart 8 split-screen magic revealed-
4 Player Multiplayer at native resolution
4 Player Multiplayer at half-width 1440p (2K)
4 Player Multiplayer at half-width 2160p (4K)

MK8 2P & 4P MP Res

---

Enthusiast Graphic Packs/Splatoon_2880p/rules.txt
Enthusiast Graphic Packs/Splatoon_4320p/rules.txt
Enthusiast Graphic Packs/Splatoon_5760p/rules.txt

This pull request gives enthusiast packs to Splatoon.

[Splatoon] Enthusiast Packs

---

Enthusiast/XCX_2880p/rules.txt
Enthusiast/XCX_4320p/rules.txt
Quality/GhostBladeHD_2160p/rules.txt
Quality/XCX_2160p/rules.txt

FIX  Intro FMV background now shows, ie works just like Cemu without any graphics packs active
FIX Regression, space after comma separator in formats row broke previous commit

XCX FMV fix, fix regression formats

---

Quality/SuperMario3DWorld_1080pUW/patches.txt

Verified all offsets and updated patches.txt with RPL checksums from all regions.

SM3dW and Captian Toad RPL module checksum update.

---

Enthusiast/BreathOfTheWild_2880p/cb0e6e8cbec4502a_0000000000000079_ps.txt
Enthusiast/BreathOfTheWild_4320p/cb0e6e8cbec4502a_0000000000000079_ps.txt
Enthusiast/BreathOfTheWild_5760p/cb0e6e8cbec4502a_0000000000000079_ps.txt
Quality/BreathOfTheWild_1080p/cb0e6e8cbec4502a_0000000000000079_ps.txt
Quality/BreathOfTheWild_1080pUW/cb0e6e8cbec4502a_0000000000000079_ps.txt
Quality/BreathOfTheWild_1440p/cb0e6e8cbec4502a_0000000000000079_ps.txt
Quality/BreathOfTheWild_1440pUW/cb0e6e8cbec4502a_0000000000000079_ps.txt
Quality/BreathOfTheWild_1800p/cb0e6e8cbec4502a_0000000000000079_ps.txt
Quality/BreathOfTheWild_2160p/cb0e6e8cbec4502a_0000000000000079_ps.txt
Quality/BreathOfTheWild_2160pUW/cb0e6e8cbec4502a_0000000000000079_ps.txt

approximate circle point spread
add one line to decide if it's in the radius
so no more squarish no more workaround

update ZL focus blur

---

Enthusiast/BreathOfTheWild_2880p/c92c1c4c0a2fb839_0000000000001e49_ps.txt
Enthusiast/BreathOfTheWild_4320p/c92c1c4c0a2fb839_0000000000001e49_ps.txt
Enthusiast/BreathOfTheWild_5760p/c92c1c4c0a2fb839_0000000000001e49_ps.txt
Quality/BreathOfTheWild_1080p/c92c1c4c0a2fb839_0000000000001e49_ps.txt
Quality/BreathOfTheWild_1080pUW/c92c1c4c0a2fb839_0000000000001e49_ps.txt
Quality/BreathOfTheWild_1440p/c92c1c4c0a2fb839_0000000000001e49_ps.txt
Quality/BreathOfTheWild_1440pUW/c92c1c4c0a2fb839_0000000000001e49_ps.txt
Quality/BreathOfTheWild_1800p/c92c1c4c0a2fb839_0000000000001e49_ps.txt
Quality/BreathOfTheWild_2160p/c92c1c4c0a2fb839_0000000000001e49_ps.txt
Quality/BreathOfTheWild_2160pUW/c92c1c4c0a2fb839_0000000000001e49_ps.txt

btw dof turning dark is because a certain 320x180 format not scaled, which isn't fixed in this (or other) shader, as i hardly understand it...

fix camera rune dof blur using the same method as zl focus

---

Enthusiast/BreathOfTheWild_2880p/81bbc347eb4b6dbc_0000000079249749_ps.txt
Enthusiast/BreathOfTheWild_4320p/81bbc347eb4b6dbc_0000000079249749_ps.txt
Enthusiast/BreathOfTheWild_5760p/81bbc347eb4b6dbc_0000000079249749_ps.txt
Quality/BreathOfTheWild_1080p/81bbc347eb4b6dbc_0000000079249749_ps.txt
Quality/BreathOfTheWild_1080pUW/81bbc347eb4b6dbc_0000000079249749_ps.txt
Quality/BreathOfTheWild_1440p/81bbc347eb4b6dbc_0000000079249749_ps.txt
Quality/BreathOfTheWild_1440pUW/81bbc347eb4b6dbc_0000000079249749_ps.txt
Quality/BreathOfTheWild_1800p/81bbc347eb4b6dbc_0000000079249749_ps.txt
Quality/BreathOfTheWild_2160p/81bbc347eb4b6dbc_0000000079249749_ps.txt
Quality/BreathOfTheWild_2160pUW/81bbc347eb4b6dbc_0000000079249749_ps.txt
Quality/BreathOfTheWild_Switch/81bbc347eb4b6dbc_0000000079249749_ps.txt

from @alexkiri 
added the unedited file by accident

leaf AA yet to be restored

---

build.sh

DRY re: copy pasting common resolution packs in

Add another indirection in build.sh so defining new packs is easier

---

appveyor.yml

Site links to the latest download dynamically, so use that for direct linking.

Multiple Releases

---

Workaround/BreathOfTheWild_!AMDShadows/ffe0e8c84f6e8da9_000003c000009269_ps.txt

Confirmed with an user with AMD, this works

[BotW] Added experimental shadow blur fix for the AMDShadows pack

---

Modifications/BreathOfTheWild_FPS++/patches.txt
Modifications/BreathOfTheWild_FPS++/rules.txt

Found at https://www.reddit.com/r/cemu/comments/7d8bxd/fps_has_been_updated_for_133/

Update BOTW FPS++ for 1.3.3

---

Workaround/BreathOfTheWild_!AMDLights/cf2e9b7aab93e342_000000000001fe49_ps.txt
Workaround/BreathOfTheWild_!AMDLights/e95d54571be1c0a9_000000000001fe49_ps.txt
Workaround/BreathOfTheWild_!AMDLights/rules.txt

- fixed dynamic light for me
- tower does not have circles anymore too, but I think it does not glow either
made by variable mashing at @alexkiri work

AMD light circles fix [Experimental]

---

Source/TwilightPrincessHD/rules.txt

Before: 
https://cdn.discordapp.com/attachments/286429969104764928/388010801287659540/unknown.png
After: 
https://cdn.discordapp.com/attachments/286429969104764928/388012769783316480/unknown.png

Fixed the menu background in TPHD.

---

Source/FistoftheNorthStar/rules.txt
Source/Wipeout3/rules.txt

A fix for the green intro videos in Wipeout 3 and support for the European version of Fist of the North Star

Minor fixes

---

Enhancement/BreathOfTheWild_NoMMTriforce/rules.txt

Unknown if the fix breaks something on AMD.

Fixed NoMMTriforce on Nvidia

---

Enhancement/HyruleWarriors_DLCFix/patches.txt
Enhancement/HyruleWarriors_DLCFix/rules.txt

[HW] DLC Fix

---

Modifications/BreathOfTheWid_static_30FPS_mod/patches.txt
Modifications/BreathOfTheWid_static_30FPS_mod/readme.txt
Modifications/BreathOfTheWid_static_30FPS_mod/rules.txt
Modifications/BreathOfTheWid_static_45FPS_mod/patches.txt
Modifications/BreathOfTheWid_static_45FPS_mod/readme.txt
Modifications/BreathOfTheWid_static_45FPS_mod/rules.txt
Modifications/BreathOfTheWid_static_60FPS_mod/patches.txt
Modifications/BreathOfTheWid_static_60FPS_mod/readme.txt
Modifications/BreathOfTheWid_static_60FPS_mod/rules.txt

After discussions I had with Slash and NoskLo, this is a short list of mods (only 30/45/60) from https://forum.cemu.info/showthread.php/421. I'd prefer it if they had a "see readme.txt" in the rules.txt name but it's probably too spammy for this repo so I followed naming convention; oh well, if users want more info to make their own fps target or get another version, they can just visit the forum thread.
PS. Be sure to read the thread or the readme of the packs if you don't understand what they are. The gist is that it's a simplified version of fps++ to fix graphics judder while it also includes the rest optimizations included in it; the caveat is it drops dynamic fps target support so the user must be able to attain said target.

Static FPS mods from https://forum.cemu.info/showthread.php/421

---

Enhancement/BreathOfTheWild_Clarity/37040a485a29d54e_00000000000003c9_ps.txt

Removed junk from the preset, probably from discord copy-paste
Should work now

Discord is leaking lol

---

Workarounds/HyruleWarriors_DLCFix/patches.txt
Workarounds/HyruleWarriors_DLCFix/rules.txt
Workarounds/HyruleWarriors_EnemyDeathFix/6e8a52b2c5236e90_0000000001fffe49_ps.txt
Workarounds/HyruleWarriors_EnemyDeathFix/fcea74ffa264fa58_000000000ffff2c9_ps.txt
Workarounds/HyruleWarriors_EnemyDeathFix/rules.txt

Add HyruleWarrior fixes updated for 1.14

HyruleWarrior crash fixes updated for 1.14

---

Enhancements/BreathOfTheWild_!AntiAliasing/0f2b9ee517917425_00000000000003c9_ps.txt
Enhancements/BreathOfTheWild_!AntiAliasing/f14bb57cd5c9cb77_00000000000003c9_ps.txt
Enhancements/BreathOfTheWild_!AntiAliasing/rules.txt
Resolutions/BreathOfTheWild_Resolution/0f2b9ee517917425_00000000000003c9_ps.txt
Resolutions/BreathOfTheWild_Resolution/f14bb57cd5c9cb77_00000000000003c9_ps.txt

Was alot of work but it is in alot better state now than it was before. Additionally resolutions shader mods were updated too.

BOTW : Fixed up Inventory Native AA and FXAA World AA

---

Mods/BreathOfTheWild_FPS++/rules.txt
Mods/BreathOfTheWild_StaticFPS/rules.txt

I Added 165fps, 55fps, and 33fps option for 165hz displays.

Added 165Hz framerates to rules.txt

---

Enhancements/WindWakerHD_NoSSAO/c2cae30e906be2d5_0000000000001e49_ps.txt
Enhancements/WindWakerHD_NoSSAO/rules.txt

Credits to BenjaminLSR for it.

Added Wind Waker HD NoSSAO gfx pack.

---

Resolutions/CODGhosts_Resolution/rules.txt

It's my first pack,I think it needs a review. I tested it and there is no error. Upscale only the main screen and not the gamepad. Will do the upscale of the gamepad soon.

Add Call of Duty: Ghosts resolution pack

---

Mods/LEGODimensions_60FPS/patches.txt
Mods/LEGODimensions_60FPS/rules.txt

This graphic pack includes 60 FPS support for base game and update.

Add 60 FPS support for Lego Dimensions.

---

Resolutions/MinecraftWiiUEdition_Resolution/rules.txt

Complete this [card](https://github.com/slashiee/cemu_graphic_packs/projects/5#card-14557744) too

add Minecraft res pack

---

Workarounds/BreathOfTheWild_Intel_FlippedLights/rules.txt
Workarounds/BreathOfTheWild_Intel_RemoveBloom/rules.txt

Removes duplicate path and renamed for clarity

Rename the Intel iGPU path

---

.github/workflows/build.yml

Build a new release only when Gfx Pack files are edited

---

Resolutions/FatalFrameProjectZero_Resolution/patches.txt

Support for the widely used version in chinese-using areas, translated by chinese folk, based on JPN version.It will be quite convenient for chinese-using areas because most players choose this translated version to play. Can you add it to the patchs.txt?Thank you!

[FatalFrameProjectZero]Resolution patch update

---

Mods/FatalFrame_60FPS/patches.txt

Support for the widely used version in chinese-using areas, translated by chinese folk and based on JPN version.It will be quite convenient for chinese-using areas because most players choose this translated version to play. Can you add it to the patchs.txt?Thank you!

[FatalFrameProjectZero]60FPS pacth update

---

Resolutions/RaymanLegends_Resolution/rules.txt

This is my first graphic pack, so it's very basic but it works. Any help polishing this would be very appreciated since I'm not very experienced with this stuff.

Add Rayman Legends resolution pack

---

Resolutions/SkylandersGiants_Resolution/rules.txt

This pack seems to work fine with me, please tell me if anything is wrong.

Add a resolution pack for Skylanders Giants

---

src/BreathOfTheWild/Mods/CameraSensitivity/patch_CameraSensitivity.asm
src/BreathOfTheWild/Mods/CameraSensitivity/rules.txt

I've separated vertical and horizontal sensitivities to easily "desync" them.
In process completely reworking this part of the pack - old address isn't used.
Changing the names may be needed to make them easier to understand.

[BotW] Added option to change vertical sensitivity + small rework

---

src/SonicBoomRiseOfLyric/Mods/DevLevelSelect/patch_DevLevelSelect.asm
src/SonicBoomRiseOfLyric/Mods/DisableIntroLogos/patch_DisableIntroLogos.asm
src/SonicBoomRiseOfLyric/Mods/UncappedFramerate/patch_UnlimitFramerate.asm

Updated all patches to support the other revisions of the initial release per region.

[Sonic Boom] Added patch support for other revisions

---

src/BreathOfTheWild/Enhancements/37040a485a29d54e_00000000000003c9_ps.txt
src/BreathOfTheWild/Enhancements/rules.txt

Add MaranBr Clarity Preset

---

src/BreathOfTheWild/Cheats/MasterModeOptions/patch_MasterModeOptions.asm
src/BreathOfTheWild/Cheats/MasterModeOptions/rules.txt

This update to Master Mode Options renames the pack, and implements NiceneNerd's [MM Damage Boost](https://gamebanana.com/mods/49885) mod. (I got permission before making this PR)
I may add the ability to change the multiplier at some point, since his patch allows for it.

Master Mode Options Update

---

src/BreathOfTheWild/Cheats/MasterModeOptions/rules.txt

Whoops, I broke Master Mode Options.

Fix Master Mode Options

---

Resolutions/RacingTransformed_Resolution/rules.txt

Resolution mod for sonic racing all stars transformed

Resolutionmod for sonic racing all stars transformed

---

src/BreathOfTheWild/Graphics/rules.txt

I added a 3:2 aspect ratio, and resolutions for it.
Closes #576

[BOTW] Add 3:2 resolutions

---

src/SonicBoomRiseOfLyric/Mods/ForceAltCostumes/patch_ForceAltCostumes.asm
src/SonicBoomRiseOfLyric/Mods/ForceAltCostumes/rules.txt

I was feeling like patching the binary would be easier than figuring out why is DLC not being acknowledged by the game. But now that it's done, it's also applicable for JP and EU release.

[Sonic Boom] Force Alt Costumes

---

Resolutions/MonsterHunter3Ultimate_Resolution/rules.txt

Enables the Software Keyboard to work on the enter name screen.
Closes #587

[MH3U]Add 0x41a to Gamepad Format filter

---

src/BreathOfTheWild/Mods/GlowingGuardianColor/rules.txt

I added this color and I find it quite beautiful.
Screenshots:

[Zelda BOTW] Add Glowing White to GlowingGuardianColor

---

Enhancements/CaptainToad_Shadows/rules.txt

I added shadow resolution for Captain Toad: Treasure Tracker.
Screenshot:

[Captain Toad] Adding Shadow Resolution

---

src/BreathOfTheWild/Enhancements/37040a485a29d54e_00000000000003c9_ps.txt
src/BreathOfTheWild/Enhancements/rules.txt

It looks more Vivid and clear.

BreathOfTheWild add a clarity preset. It looks more Vivid and clear.

---

src/NewSuperMarioBrosU/Enhancements/NegativeLOD/rules.txt

I added the ability to change the quality of textures in New Super Mario Bros U.
Screenshot:

[NSMBU] Added Texture LOD

---

SkylandersSpyrosAdventure/Graphics/rules.txt
SkylandersSpyrosAdventure/Mods/FPS/rules.txt

This is an improved graphics pack that adds:
- Fixed increased render resolution
- Adds shadow resolution option
[Footage](https://www.youtube.com/watch?v=w_ODdbu4NxI)

Skylanders Spyro's Adventure Graphics Pack

---

src/SkylandersTrapTeam/Graphics/patches.txt
src/SkylandersTrapTeam/Graphics/rules.txt

skylanders trap team aspect ration patch with fixed hud and adjusted fov

---

src/TransformersPrime/Graphics/rules.txt

Simple resolution pack, works flawless.

[New] Transformers Prime Graphics Pack

---

src/XenobladeChroniclesX/Mods/CharacterUnlockArts/patch_arts.asm

Super simple fix
it now works as intendid
I don;t know how I missed this
please merge asap so the mod can work as intended

[XCX] arts mod crash fix

---

src/SkylandersImaginators/Mods/FPS/patch_FixFallRespawn.asm
src/SkylandersImaginators/Mods/FPS/rules.txt

Continuation of #639. Fixes the last remaining part of https://github.com/cemu-project/Cemu/issues/1462.
I also modified the description in order to list the most notable issues in this game. Maybe one day they'll be fixed, but that day is not today.

[Skylanders Imaginators] Fix long fall respawn

---

src/XenobladeChroniclesX/Mods/BattleDamageModGround/patch_dmg.asm

Was ignoring user preference and only applying the divide damage mod

[XCX] Critical bug fix for XCX damage multiplication mod

---

src/ShantaeHGH/Graphics/023831cdf6638473_00000000000003c9_ps.txt
src/ShantaeHGH/Graphics/24d99fe8b4e5f576_0000000000000000_vs.txt
src/ShantaeHGH/Graphics/294904d1771460cf_0000000000000079_ps.txt
src/ShantaeHGH/Graphics/8fdd009324e987ee_0000000000000079_ps.txt
src/ShantaeHGH/Graphics/rules.txt

updates the old v2 pack to v7 so it works on modern versions of cemu
the old v2 pack can be found here:
https://github.com/cemu-project/cemu_graphic_packs/blob/939a478799c13c5ed03e8decbf952f2a7ad02366/Source/ShantaeHGH/rules.txt

[Shantae Half Genie Hero] New Graphics Pack 

---

src/LEGOCityUndercover/rules.txt

**LEGO City Undercover** is a great game but it doesn't have any graphics pack.
So I decided to create one.
Here is a comparison screenshot (The difference is obvious)

[LEGO City Undercover] Resolution Configuration + Texture Sharpness

---

src/BreathOfTheWild/Enhancements/340382e6fbbb3951_ff060c56c2a0897b_ps_msl.txt
src/BreathOfTheWild/Enhancements/37040a485a29d54e_ff060c183153097b_ps_msl.txt
src/BreathOfTheWild/Enhancements/8ff2cf86e789335f_44ab6e52279faa52_ps_msl.txt
src/BreathOfTheWild/Enhancements/cb0e6e8cbec4502a_ff060c183060c54b_ps_msl.txt

Adds support for the upcoming Metal API with the `Enhancements` pack.
It can wait until Metal is merged into Cemu.

[BOTW] Support the Metal API

---

Mods/TwilightPrincessHD_DisableMirror/patches.txt
Mods/TwilightPrincessHD_DisableMirror/rules.txt

Small mod that disables the mirroring from the Wii version in Hero Mode.

[TwilightPrincessHD] disable mirroring in Hero Mode (Mod)

---

src/NewSuperMarioBrosU/Graphics/rules.txt

Fixes the following issue: #706

[NSMBU]: Fixes issue with videos

---

src/LEGOCityUndercover/Graphics/rules.txt

Improves the quality of distant textures.

[Lego City Undercover] Add Anisotropic Filtering

---

src/SuperMario3DWorld/Cheats/InfiniteLives/patch_InfiniteLives.asm
src/SuperMario3DWorld/Cheats/InfiniteLives/rules.txt
src/SuperMario3DWorld/Cheats/InfiniteTime/patch_InfiniteTime.asm
src/SuperMario3DWorld/Cheats/InfiniteTime/rules.txt

[Super Mario 3D World] Add cheats for infinite time/lives
